codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: false
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true

comment:
  layout: 'reach,diff,flags,files'
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - 'tests'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/test/**'
  - '**/test-utils/**'
  - '**/*.config.ts'
  - '**/*.config.js'
  - 'node_modules'
