export default {
  hooks: {
    fileHeaders: {
      generatedHeader: () => [
        'DO NOT EDIT THIS FILE DIRECTLY.',
        'Auto-generated from src/styles/design-tokens.json by Style Dictionary.',
        'Run `npm run build:tokens` to regenerate.',
      ],
    },
  },
  source: ['src/styles/design-tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: '',
      files: [
        {
          destination: 'src/styles/tokens.css',
          format: 'css/variables',
          options: {
            fileHeader: 'generatedHeader',
            selector: ':root',
          },
        },
      ],
    },
  },
};
