import productsJson from '@/data/br/products.json';
import partsJson from '@/data/br/parts.json';
import productPartsJson from '@/data/br/product-parts.json';
import accessoriesJson from '@/data/br/accessories.json';
import type { Accessory, CropBox, Part, PartVariant, Product, ProductParts } from './types';

/** Generated by `npm run data:br`. */
export const PRODUCTS = productsJson as Product[];
/** Hand-curated. */
export const PARTS = partsJson as Part[];
/** Hand-curated. */
export const PRODUCT_PARTS = productPartsJson as ProductParts[];
/** Hand-curated. */
export const ACCESSORIES = accessoriesJson as Accessory[];

export interface ResolvedPart {
  part: Part;
  quantity: number;
  /** How the part looks in this product, when recorded. */
  variant?: PartVariant;
}

export interface PartSource {
  product: Product;
  quantity: number;
}

/** One appearance of a part: the variant and the product it ships in. */
export interface PartVariantSource {
  product: Product;
  variant: PartVariant;
}

/** Named parts in a product, or null when the product has no mapping. */
export function resolveProductParts(
  code: string,
  parts: Part[] = PARTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): ResolvedPart[] | null {
  const entry = productParts.find((e) => e.productCode === code);
  if (!entry) return null;
  return entry.parts.flatMap(({ partId, quantity, variant }) => {
    const part = parts.find((p) => p.id === partId);
    return part ? [{ part, quantity, ...(variant && { variant }) }] : [];
  });
}

/** Products that contain a part, in catalog order. Empty when no mapping references it. */
export function findPartSources(
  partId: string,
  products: Product[] = PRODUCTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): PartSource[] {
  return products.flatMap((product) => {
    const quantity = productParts
      .find((e) => e.productCode === product.code)
      ?.parts.find((p) => p.partId === partId)?.quantity;
    return quantity ? [{ product, quantity }] : [];
  });
}

/** Every recorded variant of a part, in catalog (product code) order. */
export function findPartVariants(
  partId: string,
  products: Product[] = PRODUCTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): PartVariantSource[] {
  return products.flatMap((product) => {
    const variant = productParts
      .find((e) => e.productCode === product.code)
      ?.parts.find((p) => p.partId === partId)?.variant;
    return variant ? [{ product, variant }] : [];
  });
}

/** The product shot and crop box picturing a variant, or null when it has no usable image. */
export function variantShot(
  product: Product,
  variant: PartVariant | undefined,
): { path: string; crop: CropBox } | null {
  const image = variant?.image;
  const path = image && product.images[image.shot - 1];
  return image && path ? { path, crop: image.crop } : null;
}

/** A catalogued item an inventory instance can reference: a part or an accessory. */
export type CatalogItem =
  { kind: 'part'; part: Part } | { kind: 'accessory'; accessory: Accessory };

/** The part or accessory an item id names, or null when the catalog has neither. */
export function resolveItem(
  itemId: string,
  parts: Part[] = PARTS,
  accessories: Accessory[] = ACCESSORIES,
): CatalogItem | null {
  const part = parts.find((p) => p.id === itemId);
  if (part) return { kind: 'part', part };
  const accessory = accessories.find((a) => a.id === itemId);
  return accessory ? { kind: 'accessory', accessory } : null;
}

/** One line of a product's trackable contents. */
export interface ProductContentLine {
  item: CatalogItem;
  quantity: number;
  /** How the part looks in this product, when recorded. Never set for accessories. */
  variant?: PartVariant;
}

/**
 * Every trackable item in a product with its quantity: mapped parts first,
 * then mapped accessories. Null when the product has no mapping; printed
 * contents without a mapping line are omitted.
 */
export function resolveProductContents(
  code: string,
  parts: Part[] = PARTS,
  accessories: Accessory[] = ACCESSORIES,
  productParts: ProductParts[] = PRODUCT_PARTS,
): ProductContentLine[] | null {
  const entry = productParts.find((e) => e.productCode === code);
  if (!entry) return null;
  const partLines = entry.parts.flatMap(({ partId, quantity, variant }) => {
    const item = resolveItem(partId, parts, []);
    return item ? [{ item, quantity, ...(variant && { variant }) }] : [];
  });
  const accessoryLines = (entry.accessories ?? []).flatMap(({ accessoryId, quantity }) => {
    const item = resolveItem(accessoryId, [], accessories);
    return item ? [{ item, quantity }] : [];
  });
  return [...partLines, ...accessoryLines];
}

/** Products whose mapping lists an accessory, in catalog order. */
export function findAccessorySources(
  accessoryId: string,
  products: Product[] = PRODUCTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): PartSource[] {
  return products.flatMap((product) => {
    const quantity = productParts
      .find((e) => e.productCode === product.code)
      ?.accessories?.find((a) => a.accessoryId === accessoryId)?.quantity;
    return quantity ? [{ product, quantity }] : [];
  });
}

/** Products a purchase can be recorded for: those with a contents mapping, by code. */
export function purchasableProducts(
  products: Product[] = PRODUCTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): Product[] {
  return products
    .filter((product) => productParts.some((e) => e.productCode === product.code))
    .sort((a, b) => a.code.localeCompare(b.code));
}
