import productsJson from '@/data/br/products.json';
import partsJson from '@/data/br/parts.json';
import productPartsJson from '@/data/br/product-parts.json';
import type { Part, Product, ProductParts } from './types';

/** Generated by `npm run data:br`. */
export const PRODUCTS = productsJson as Product[];
/** Hand-curated. */
export const PARTS = partsJson as Part[];
/** Hand-curated. */
export const PRODUCT_PARTS = productPartsJson as ProductParts[];

export interface ResolvedPart {
  part: Part;
  quantity: number;
}

export interface PartSource {
  product: Product;
  quantity: number;
}

/** Named parts in a product, or null when the product has no mapping. */
export function resolveProductParts(
  code: string,
  parts: Part[] = PARTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): ResolvedPart[] | null {
  const entry = productParts.find((e) => e.productCode === code);
  if (!entry) return null;
  return entry.parts.flatMap(({ partId, quantity }) => {
    const part = parts.find((p) => p.id === partId);
    return part ? [{ part, quantity }] : [];
  });
}

/** Products that contain a part, in catalog order. Empty when no mapping references it. */
export function findPartSources(
  partId: string,
  products: Product[] = PRODUCTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): PartSource[] {
  return products.flatMap((product) => {
    const quantity = productParts
      .find((e) => e.productCode === product.code)
      ?.parts.find((p) => p.partId === partId)?.quantity;
    return quantity ? [{ product, quantity }] : [];
  });
}
