import productsJson from '@/data/br/products.json';
import partsJson from '@/data/br/parts.json';
import productPartsJson from '@/data/br/product-parts.json';
import type { CropBox, Part, PartVariant, Product, ProductParts } from './types';

/** Generated by `npm run data:br`. */
export const PRODUCTS = productsJson as Product[];
/** Hand-curated. */
export const PARTS = partsJson as Part[];
/** Hand-curated. */
export const PRODUCT_PARTS = productPartsJson as ProductParts[];

export interface ResolvedPart {
  part: Part;
  quantity: number;
  /** How the part looks in this product, when recorded. */
  variant?: PartVariant;
}

export interface PartSource {
  product: Product;
  quantity: number;
}

/** One appearance of a part: the variant and the product it ships in. */
export interface PartVariantSource {
  product: Product;
  variant: PartVariant;
}

/** Named parts in a product, or null when the product has no mapping. */
export function resolveProductParts(
  code: string,
  parts: Part[] = PARTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): ResolvedPart[] | null {
  const entry = productParts.find((e) => e.productCode === code);
  if (!entry) return null;
  return entry.parts.flatMap(({ partId, quantity, variant }) => {
    const part = parts.find((p) => p.id === partId);
    return part ? [{ part, quantity, ...(variant && { variant }) }] : [];
  });
}

/** Products that contain a part, in catalog order. Empty when no mapping references it. */
export function findPartSources(
  partId: string,
  products: Product[] = PRODUCTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): PartSource[] {
  return products.flatMap((product) => {
    const quantity = productParts
      .find((e) => e.productCode === product.code)
      ?.parts.find((p) => p.partId === partId)?.quantity;
    return quantity ? [{ product, quantity }] : [];
  });
}

/** Every recorded variant of a part, in catalog (product code) order. */
export function findPartVariants(
  partId: string,
  products: Product[] = PRODUCTS,
  productParts: ProductParts[] = PRODUCT_PARTS,
): PartVariantSource[] {
  return products.flatMap((product) => {
    const variant = productParts
      .find((e) => e.productCode === product.code)
      ?.parts.find((p) => p.partId === partId)?.variant;
    return variant ? [{ product, variant }] : [];
  });
}

/** The product shot and crop box picturing a variant, or null when it has no usable image. */
export function variantShot(
  product: Product,
  variant: PartVariant | undefined,
): { path: string; crop: CropBox } | null {
  const image = variant?.image;
  const path = image && product.images[image.shot - 1];
  return image && path ? { path, crop: image.crop } : null;
}
