/** Battle style a machine or kit is built around. Tools (e.g. arenas) have none. */
export type Style = 'upper' | 'spin' | 'dash';

export type ProductType = 'starter-set' | 'booster-set' | 'tool';

/** Part slots a machine is assembled from. */
export type Slot = 'cowl' | 'bumper' | 'tire' | 'chassis';

/** Everything a box can list under its contents: part slots plus non-part items. */
export type ContentsKey = Slot | 'charger' | 'sticker' | 'body';

export interface Price {
  amount: number;
  currency: 'JPY';
  taxIncluded: boolean;
}

/** One released product. Generated by `npm run data:br` — never hand-edited. */
export interface Product {
  /** BR code, e.g. `BR-01`. Stable id. */
  code: string;
  nameEn: string;
  nameJa: string;
  type: ProductType;
  style: Style | null;
  price: Price;
  /** ISO date, `YYYY-MM-DD`. */
  releaseDate: string;
  /** Slot-level counts as printed on the product page. */
  contents: Partial<Record<ContentsKey, number>>;
  /** Bandai item path segment, e.g. `01_21000`. Not ordered by product code. */
  sourceId: string;
  sourceUrl: string;
  /** Official manual link, when the item page has one. Opens Bandai's interstitial page, not the PDF. */
  manualUrl?: string;
}

/** One named part. Hand-curated. */
export interface Part {
  /** `<slot>:<slug>`, e.g. `bumper:dual-blade`. Stable id. */
  id: string;
  slot: Slot;
  nameEn: string;
  nameJa: string;
}

export interface ProductPartQuantity {
  partId: string;
  quantity: number;
}

/** Which named parts ship in one product. Hand-curated. */
export interface ProductParts {
  productCode: string;
  parts: ProductPartQuantity[];
  /** Where this mapping was confirmed from. */
  source: string;
}

export const SLOTS: Slot[] = ['cowl', 'bumper', 'tire', 'chassis'];
